# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://ec2-34-220-162-82.us-west-2.compute.amazonaws.com:5002/auth
Content-Type: application/json

{"username":  "PL19-16", "password":  "PL19-16-oa"}

###

POST http://ec2-34-220-162-82.us-west-2.compute.amazonaws.com:5002/user/PL19-16/devices
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6MTM3MCwiaWF0IjoxNTU5OTg1NTUwLCJuYmYiOjE1NTk5ODU1NTAsImV4cCI6MTU2MjU3NzU1MH0.A7gQP3-dJe6XR6sCVKV-wzhsBJYgSleDelpkYrfKGMs
Content-Type: application/json

{"device_mac":  "39:05:62:2D:C8:B8", "nickname":  "my-nick2", "configuration": "some configuration here"}

###

GET http://ec2-34-220-162-82.us-west-2.compute.amazonaws.com:5002/user/PL19-16/logs
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGl0eSI6MTM3MCwiaWF0IjoxNTYzMTMyMDM0LCJuYmYiOjE1NjMxMzIwMzQsImV4cCI6MTU2NTcyNDAzNH0.cjUGWSdFh7XgXROdJlZpTvdg5uyNMYE_FU96H3IL0tg

> {%
client.log(JSON.parse(response.body
.replace(/\\/g, '')
.replace(/\\\\/g, '')
.replace(/""/g, '"')
.replace(/"{/g, '{')
.replace(/}"/g, '}')
));
%}
###
