# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:3000/apartment/updateProgTemp
Content-Type: application/json

{
  "id": 1,
  "type": "Bagno",
  "progTemp": 22,
  "sensor": {
    "id": "s:C3:50:E3:56:2F:68"
  },
  "actuator": {
    "id":"a:B8:E6:2D:68:34:FD"
  }
}

###
