#!/bin/bash

# print current directory
echo $PWD
echo "app is starting"
sleep 5

# run node server
cd ../../usr/bin/tlc-app/scripts
./runNode &

# open page
chromium-browser http://localhost/ui/index.html
